# Generated by Django 4.1.2 on 2022-10-19 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('link', models.URLField(verbose_name='Link')),
                ('picture', models.URLField(verbose_name='Foto')),
                ('nb_album', models.SmallIntegerField(verbose_name='Número de álbum')),
                ('nb_fan', models.IntegerField(verbose_name='Número de fans')),
                ('radio', models.BooleanField(default=True, verbose_name='Radio')),
                ('type', models.CharField(choices=[('genre', 'Género'), ('track', 'Canción'), ('album', 'Album'), ('artist', 'Artista')], default=None, max_length=10, verbose_name='Tipo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
    ]
