# Generated by Django 4.1.2 on 2022-10-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='type',
            field=models.CharField(default='album', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='type',
            field=models.CharField(default='genre', max_length=10, verbose_name='Tipo'),
        ),
    ]
