# Generated by Django 4.1.2 on 2022-10-19 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '__first__'),
        ('artists', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('title_short', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título corto')),
                ('link', models.URLField(verbose_name='Link')),
                ('duration', models.SmallIntegerField(blank=True, null=True, verbose_name='Tiempo de duración')),
                ('track_position', models.SmallIntegerField(blank=True, null=True, verbose_name='Posición')),
                ('disk_number', models.SmallIntegerField(blank=True, null=True, verbose_name='Número de disco')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento')),
                ('type', models.CharField(choices=[('genre', 'Género'), ('track', 'Canción'), ('album', 'Album'), ('artist', 'Artista')], default=None, max_length=10, verbose_name='Tipo')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_artist', to='albums.album', verbose_name='Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artist', to='artists.artist', verbose_name='Artista')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
